### ISSUE TITLE
long title cannot split into multiple lines.

### ISSUE THREAD

**Issue by dreistein543** [gaksaray/AOM-LaTeX-template#1]
Thank you for your work! I use your template on overleaf, it helps me a lot.

I notice a tiny problem with the display of title.

in your template, the title appears 3 times:
✅ at the author-information page (the first page) 
❌ at the abstract page (the second page)
❌ at the text page (the third page)

a long title at the author-information page can split itself automatically and displays well

however, title at the next two pages can only be displayed in a single line no matter how long.

I have tried to split title manually, but fails.

I hope if you can fix it soon

or could you please offer me a short snippet to help me fix it

**Comment by gaksaray** [comment]
Thanks @dreistein543 for point this out. I fixed it so that long titles behave as expected now. If you want to manually break the title into multiple lines, use `\break` instead of other options such as `\\` or `\newline`.
