### ISSUE TITLE
allow multiple plots display in one page

### ISSUE THREAD

**Issue by dreistein543** [gaksaray/AOM-LaTeX-template#2]
Hi Gorkem,

My paper has 41 pages with your template, while AOM ask for a maximum 40 pages.

I notice that your template puts my plots on different pages even if I set a very small size of them, it looks nice but doesn't space-saving.

I wonder if there is a flexible way to put them on one page (or just cancel the `force page break`), like what your template does in the appendix part.

**Comment by gaksaray** [comment]
This is the default behavior of `endfloat` package:

> Endfloat places `\efloatseparator` between the floats in their respective files. By default it is defined to be `\clearpage` forcing one float per page.

[AOM Journal's Style Guide](https://aom.org/docs/default-source/events/amjstyleguide.aspx) suggests: 

> Number tables and figures consecutively (one series for tables, one for figures). Place them at the end of your manuscript, but indicate the position of each in the text as follows.

I added a line (see the [commit](https://github.com/gaksaray/AOM-LaTeX-template/commit/8f94d683559611d7f7e12a2a83c8c0f5db354143)) to optionally disable having to `\clearpage` after each float. Note that this can only be done for portrait floats. The `landscape` environment still clears the page after each figure or table.
